package com.lovetropics.extras.client.model_modifer.types;

import com.lovetropics.extras.LTExtras;
import com.lovetropics.extras.client.model_modifer.ModelApplier;
import com.lovetropics.extras.model_modifer.types.UnitType;
import net.minecraft.client.animation.AnimationChannel;
import net.minecraft.client.animation.AnimationDefinition;
import net.minecraft.client.animation.Keyframe;
import net.minecraft.client.animation.KeyframeAnimation;
import net.minecraft.client.animation.KeyframeAnimations;
import net.minecraft.client.model.EntityModel;
import net.minecraft.client.renderer.entity.state.LivingEntityRenderState;
import net.minecraft.util.context.ContextKey;
import net.minecraft.world.entity.AnimationState;

import java.util.WeakHashMap;

/**
 * LTExtras
 * FIRE EMOJI, FIRE EMOJI, FIRE EMOJI
 * THIS IS MOSTLY A PROVE OF CONCEPT, THERE MOST LIKELY A BETTER WAY TO DO THIS, BUT THIS WORKS FOR NOW
 */
public class DanceApplier implements ModelApplier.Unit {

    private final WeakHashMap<EntityModel<?>, AnimationState> animationStates = new WeakHashMap<>();
    private final WeakHashMap<EntityModel<?>, KeyframeAnimation> entityAnimationStates = new WeakHashMap<>();
    private static final ContextKey<Integer> ANIMATION_KEY = new ContextKey<>(LTExtras.id("dance_animation_tick_count"));

    @Override
    public void applyToModel(UnitType data, LivingEntityRenderState state, EntityModel<?> model) {
        if (model.root().hasChild("head")) {
            AnimationState animationState1 = animationStates.computeIfAbsent(model, e -> new AnimationState());
            animationState1.startIfStopped(state.getRenderDataOrDefault(ANIMATION_KEY, 0));
            KeyframeAnimation animation = entityAnimationStates.computeIfAbsent(model, entityModel -> TEST_ANIAMTION.bake(entityModel.root()));

            animation.apply(animationState1, state.ageInTicks);
        }
    }

    public static final AnimationDefinition TEST_ANIAMTION = AnimationDefinition.Builder.withLength(4f).looping()
            .addAnimation("head",
                    new AnimationChannel(AnimationChannel.Targets.POSITION,
                            new Keyframe(0f, KeyframeAnimations.posVec(0f, -0.16f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.041676664f, KeyframeAnimations.posVec(0f, -0.2f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.08343333f, KeyframeAnimations.posVec(0f, -0.18f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.125f, KeyframeAnimations.posVec(0f, -0.12f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.16766666f, KeyframeAnimations.posVec(0f, -0.02f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.20834331f, KeyframeAnimations.posVec(0f, 0.08f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.24999999999999997f, KeyframeAnimations.posVec(0f, 0.16f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.29167663f, KeyframeAnimations.posVec(0f, 0.2f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.3433333f, KeyframeAnimations.posVec(0f, 0.18f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.375f, KeyframeAnimations.posVec(0f, 0.12f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.4167667f, KeyframeAnimations.posVec(0f, 0.02f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.45834337f, KeyframeAnimations.posVec(0f, -0.08f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.5f, KeyframeAnimations.posVec(0f, -0.16f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.5416766f, KeyframeAnimations.posVec(0f, -0.2f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.5834333f, KeyframeAnimations.posVec(0f, -0.18f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.6249999999999999f, KeyframeAnimations.posVec(0f, -0.12f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.6766665f, KeyframeAnimations.posVec(0f, -0.02f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.7083431f, KeyframeAnimations.posVec(0f, 0.08f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.7499999999999998f, KeyframeAnimations.posVec(0f, 0.16f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.7916764f, KeyframeAnimations.posVec(0f, 0.2f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.834333f, KeyframeAnimations.posVec(0f, 0.18f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.8749999999999997f, KeyframeAnimations.posVec(0f, 0.12f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.9167663f, KeyframeAnimations.posVec(0f, 0.02f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.9583429f, KeyframeAnimations.posVec(0f, -0.08f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.9999999999999996f, KeyframeAnimations.posVec(0f, -0.16f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(1.0416763f, KeyframeAnimations.posVec(0f, -0.2f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(1.083433f, KeyframeAnimations.posVec(0f, -0.18f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(1.1249999999999998f, KeyframeAnimations.posVec(0f, -0.12f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(1.1676665f, KeyframeAnimations.posVec(0f, -0.02f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(1.2083433f, KeyframeAnimations.posVec(0f, 0.08f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(1.25f, KeyframeAnimations.posVec(0f, 0.16f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(1.2916767f, KeyframeAnimations.posVec(0f, 0.2f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(1.3433335f, KeyframeAnimations.posVec(0f, 0.18f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(1.3750000000000002f, KeyframeAnimations.posVec(0f, 0.12f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(1.416767f, KeyframeAnimations.posVec(0f, 0.02f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(1.4583437f, KeyframeAnimations.posVec(0f, -0.08f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(1.5000000000000004f, KeyframeAnimations.posVec(0f, -0.16f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(1.5416772f, KeyframeAnimations.posVec(0f, -0.2f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(1.583434f, KeyframeAnimations.posVec(0f, -0.18f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(1.6250000000000007f, KeyframeAnimations.posVec(0f, -0.12f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(1.6766674f, KeyframeAnimations.posVec(0f, -0.02f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(1.7083441f, KeyframeAnimations.posVec(0f, 0.08f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(1.7500000000000009f, KeyframeAnimations.posVec(0f, 0.16f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(1.7916776f, KeyframeAnimations.posVec(0f, 0.2f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(1.8343344f, KeyframeAnimations.posVec(0f, 0.18f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(1.875000000000001f, KeyframeAnimations.posVec(0f, 0.12f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(1.9167679f, KeyframeAnimations.posVec(0f, 0.02f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(1.9583446f, KeyframeAnimations.posVec(0f, -0.08f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(2.0000000000000013f, KeyframeAnimations.posVec(0f, -0.16f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(2.041678f, KeyframeAnimations.posVec(0f, -0.2f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(2.0834344f, KeyframeAnimations.posVec(0f, -0.18f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(2.125000000000001f, KeyframeAnimations.posVec(0f, -0.12f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(2.1676674f, KeyframeAnimations.posVec(0f, -0.02f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(2.208344f, KeyframeAnimations.posVec(0f, 0.08f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(2.2500000000000004f, KeyframeAnimations.posVec(0f, 0.16f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(2.291677f, KeyframeAnimations.posVec(0f, 0.2f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(2.3433335f, KeyframeAnimations.posVec(0f, 0.18f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(2.375f, KeyframeAnimations.posVec(0f, 0.12f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(2.4167665f, KeyframeAnimations.posVec(0f, 0.02f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(2.458343f, KeyframeAnimations.posVec(0f, -0.08f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(2.4999999999999996f, KeyframeAnimations.posVec(0f, -0.16f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(2.541676f, KeyframeAnimations.posVec(0f, -0.2f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(2.5834326f, KeyframeAnimations.posVec(0f, -0.18f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(2.624999999999999f, KeyframeAnimations.posVec(0f, -0.12f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(2.6766656f, KeyframeAnimations.posVec(0f, -0.02f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(2.708342f, KeyframeAnimations.posVec(0f, 0.08f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(2.7499999999999987f, KeyframeAnimations.posVec(0f, 0.16f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(2.791675f, KeyframeAnimations.posVec(0f, 0.2f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(2.8343317f, KeyframeAnimations.posVec(0f, 0.18f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(2.8749999999999982f, KeyframeAnimations.posVec(0f, 0.12f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(2.9167647f, KeyframeAnimations.posVec(0f, 0.02f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(2.9583413f, KeyframeAnimations.posVec(0f, -0.08f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(2.999999999999998f, KeyframeAnimations.posVec(0f, -0.16f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(3.0416743f, KeyframeAnimations.posVec(0f, -0.2f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(3.083431f, KeyframeAnimations.posVec(0f, -0.18f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(3.1249999999999973f, KeyframeAnimations.posVec(0f, -0.12f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(3.167664f, KeyframeAnimations.posVec(0f, -0.02f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(3.2083404f, KeyframeAnimations.posVec(0f, 0.08f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(3.249999999999997f, KeyframeAnimations.posVec(0f, 0.16f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(3.2916734f, KeyframeAnimations.posVec(0f, 0.2f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(3.34333f, KeyframeAnimations.posVec(0f, 0.18f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(3.3749999999999964f, KeyframeAnimations.posVec(0f, 0.12f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(3.416763f, KeyframeAnimations.posVec(0f, 0.02f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(3.4583333333333295f, KeyframeAnimations.posVec(0f, -0.08f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(3.499999999999996f, KeyframeAnimations.posVec(0f, -0.16f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(3.5416725f, KeyframeAnimations.posVec(0f, -0.2f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(3.583429f, KeyframeAnimations.posVec(0f, -0.18f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(3.6249999999999956f, KeyframeAnimations.posVec(0f, -0.12f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(3.676662f, KeyframeAnimations.posVec(0f, -0.02f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(3.7083333333333286f, KeyframeAnimations.posVec(0f, 0.08f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(3.749999999999995f, KeyframeAnimations.posVec(0f, 0.16f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(3.7916716f, KeyframeAnimations.posVec(0f, 0.2f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(3.834328f, KeyframeAnimations.posVec(0f, 0.18f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(3.8749999999999947f, KeyframeAnimations.posVec(0f, 0.12f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(3.916761f, KeyframeAnimations.posVec(0f, 0.02f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(3.9583333333333277f, KeyframeAnimations.posVec(0f, -0.08f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(4f, KeyframeAnimations.posVec(0f, -0.16f, 0f),
                                    AnimationChannel.Interpolations.LINEAR)))
            .build();
}
