mod_id=ltextras
mod_version=25.0
release_type=release
minecraft_version=26.1.2
minecraft_version_range=[26.1,26.2)
loader_version_range=[4,)
neo_version=26.1.2.31-beta
neo_version_range=[26.1.2.31-beta,)

registrate_version=1.3.0+9
ltlib_version=[3.5,4)
placeholder_api_version=[2.8,3.0)
#fusion_version=1.2.11a-neoforge-mc1.21.6
#fusion_version_range=[1.2,)

org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true
