modLoader="javafml"
loaderVersion="[36,)"
issueTrackerURL="https://github.com/LoveTropics/LTExtras/issues"
license="All Rights Reserved"

[[mods]]
modId="ltextras"
version="${file.jarVersion}"
displayName="LTExtras"
displayURL="https://lovetropics.com"
credits=""
authors="tterrag"
description='''
Extra content for the LoveTropics map build.
'''

[[dependencies.ltextras]] 
    modId="forge"
    mandatory=true 
    versionRange="[31.2.44,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.create]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2,1.16)"
    ordering="NONE"
    side="BOTH"
