modLoader="javafml" #mandatory
loaderVersion="[25,)" #mandatory (24 is current forge version)
issueTrackerURL="https://github.com/LoveTropics/LTExtras/issues"

[[mods]]
modId="ltextras"
version="${file.jarVersion}"
displayName="LTExtras" #mandatory
displayURL="https://lovetropics.com"
#logoFile="examplemod.png" #optional
credits="" #optional
authors="tterrag" #optional
description='''
Extra content for the LoveTropics map build.
'''

[[dependencies.ltextras]] 
    modId="forge"
    mandatory=true 
    versionRange="[31.2.44,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.create]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2,1.16)"
    ordering="NONE"
    side="BOTH"