modLoader="javafml"
loaderVersion="[40,)"
issueTrackerURL="https://github.com/LoveTropics/LTExtras/issues"
license="All Rights Reserved"

[[mods]]
modId="ltextras"
version="${file.jarVersion}"
displayName="LTExtras"
displayURL="https://lovetropics.org"
credits=""
authors="tterrag"
description='''
Extra content for the LoveTropics map build.
'''

[[dependencies.ltextras]] 
    modId="forge"
    mandatory=true 
    versionRange="[40.1.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.ltextras]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.ltextras]]
    modId="create"
    mandatory=false
    versionRange="*"
    ordering="AFTER"
    side="BOTH"
